### ISSUE TITLE
Your document includes text that's not compatible with the Windows-1252 character set

### ISSUE THREAD

**Issue by catalin88** [spree-contrib/spree_print_invoice#113]
I'm getting the following error for using local language characters:

raise Prawn::Errors::IncompatibleStringEncoding,
       "Your document includes text that's not compatible with the Windows-1252 character set.\n" \
       "If you need full UTF-8 support, use TTF fonts instead of PDF's built-in fonts\n."

How can I solve this, how can I use TTF fonts instead of PDF's built-in fonts for Prawn ?

I have found what appears to be a solution on stackoverflow: http://stackoverflow.com/questions/37286976/ruby-how-to-use-different-fonts-in-prawn

But I'm not sure where to insert this code:

```
Prawn::Document.generate("output.pdf") do
  font_families.update("Arial" => {
    :normal => "/assets/fonts/Arial.ttf",
    :italic => "/assets/fonts/Arial Italic.ttf",
  })
  font "Arial"
end
```

Any ideas ?

**Comment by catalin88** [comment]
So, what's the code to change the font used to a custom one ?

To change this 

`preference :font_face,        :string,  default: 'Helvetica'`

here:

https://github.com/spree-contrib/spree_print_invoice/blob/fa7502f6af6e315d788d4ecd9ba3ad6d3e5ad441/lib/spree/print_invoice_setting.rb

**Comment by aman29april** [comment]
I am also getting the same issue. Any solution?

**Comment by aman29april** [comment]
@catalin88 
I have found solution.

You can write below code inside _base.pdf.prawn, inside block
prawn_document(force_download: true) do |pdf|


end

`pdf.font_families.update(
    "Helvetica" => {
      normal: Rails.root.join('app', 'assets/fonts', 'HelveticaNeueW01-65Medium.ttf').to_s,
      bold: Rails.root.join('app', 'assets/fonts', 'HelveticaNeueW01-65Medium.ttf').to_s,
      italic: Rails.root.join('app', 'assets/fonts', 'HelveticaNeueW01-65Medium.ttf').to_s,
      bold_italic: Rails.root.join('app', 'assets/fonts', 'HelveticaNeueW01-65Medium.ttf').to_s
    }
  )`

**Comment by imgarylai** [comment]
This issue should have been resolved in the latest version. #148
