### ISSUE TITLE
Asset url

### ISSUE THREAD

**Issue by paulhuisman** [spree-contrib/spree_print_invoice#70]
Hi futhr,

Nice work on this gem! I was trying to add the following to your _print.pdf.prawn template:

`image asset_url 'logo.svg' , :at => [0,720], :scale => logo_scale`

But i get a "image not found", while the url (http://localhost:3000/assets/logo.svg) actually exist.

Do you know how to add this image?

**Comment by peterberkenbosch** [comment]
Try assets/images

**Comment by paulhuisman** [comment]
Thanks for your swift response. I think it might have something to do with http://stackoverflow.com/questions/11560455/prawn-import-image-from-url.

I do not think the solution applies to my _print.pdf.prawn template though.

**Comment by paulhuisman** [comment]
Solved it with using the correct method name:

`Spree::PrintInvoice::Config.set(print_invoice_logo_path: 'logo.jpg' )`

In the documentation it shows the wrong method name, 'logo_path'

**Comment by peterberkenbosch** [comment]
ah, that makes sense! Thanks. Will update the readme.

**Comment by peterberkenbosch** [comment]
Not sure how that should actually work? What branch are you using? It's logo_path on 3-0-stable

**Comment by paulhuisman** [comment]
Ah, my bad.. was looking at the wrong README. I'm on 2-3-stable. Sorry!
